name: social_app_demo
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  freezed_annotation: ^1.1.0
  analyzer: ^3.2.0
  get: ^4.6.1
  dartz: ^0.10.1
  equatable: ^2.0.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.1.7
  freezed: ^1.1.1
  # json_serializable: ^6.1.4

flutter:

  uses-material-design: true

  assets:
    - assets/profile.png